POST http://localhost:3000/stream/start HTTP/1.1
content-type: application/json

{
    "streamKey": "test123",
    "inputSource": "audio_0.mp4"
}

### Switch to idle
POST http://localhost:3000/stream/idle HTTP/1.1
content-type: application/json

{
    "streamKey": "test123"
}


### Switch to speaking
POST http://localhost:3000/stream/speaking HTTP/1.1
content-type: application/json

{
    "streamKey": "test123"
}

### Switch to welcome
POST http://localhost:3000/stream/welcome HTTP/1.1
content-type: application/json

{
    "streamKey": "test123"
}


### Stop stream
DELETE http://localhost:3000/stream/stop/test123 HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}



### Get all sessions
GET http://localhost:3000/stream/sessions HTTP/1.1



### stop
POST http://localhost:3000/stream/stop/test123 HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}